# Generated by Django 5.0.2 on 2024-02-22 23:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titlu", models.CharField(max_length=100, unique=True)),
                ("url", models.CharField(max_length=1000)),
                (
                    "plasament",
                    models.IntegerField(
                        choices=[
                            (1, "Link 1"),
                            (2, "Link 2"),
                            (3, "Link 3"),
                            (4, "Link buton"),
                        ],
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Link-uri",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titlu", models.CharField(max_length=100, unique=True)),
                ("imagine", models.ImageField(null=True, upload_to="blog/images/")),
                (
                    "continut",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Continut"
                    ),
                ),
                ("data_creare", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Anunt",
                "verbose_name_plural": "Anunturi",
                "ordering": ["-data_creare"],
            },
        ),
    ]
