# Generated by Django 5.0.2 on 2024-02-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Imagine 1", models.FileField(null=True, upload_to="blog/images/")),
                ("Imagine 2", models.FileField(null=True, upload_to="blog/images/")),
                ("titlu", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Slider",
                "verbose_name_plural": "Slidere",
            },
        ),
    ]
