# Generated by Django 4.1.4 on 2023-03-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specializare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('plan_de_invatamant', models.FileField(blank=True, null=True, upload_to='programe_de_studii/planuri_de_invatamant/', verbose_name='Plan de invatamant')),
                ('ciclu', models.CharField(choices=[('Licenta', 'Licenta'), ('Master', 'Master')], default='Licenta', max_length=50)),
            ],
            options={
                'verbose_name': 'Program de studii',
                'verbose_name_plural': 'Programe de studii',
            },
        ),
        migrations.CreateModel(
            name='Orar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an', models.IntegerField(choices=[(1, 'Anul 1'), (2, 'Anul 2'), (3, 'Anul 3'), (4, 'Anul 4')], default=1)),
                ('semestru', models.IntegerField(choices=[(1, 'Semestrul 1'), (2, 'Semestrul 2')], default=1)),
                ('orar', models.FileField(blank=True, null=True, upload_to='programe_de_studii/orare/', verbose_name='Orar')),
                ('specializare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orare', to='programe_de_studii.specializare')),
            ],
            options={
                'verbose_name': 'Orar',
                'verbose_name_plural': 'Orare',
            },
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an', models.IntegerField(choices=[(1, 'Anul 1'), (2, 'Anul 2'), (3, 'Anul 3'), (4, 'Anul 4')], default=1)),
                ('semestru', models.IntegerField(choices=[(1, 'Semestrul 1'), (2, 'Semestrul 2')], default=1)),
                ('nume', models.CharField(max_length=50)),
                ('fisa_disciplinei', models.FileField(blank=True, null=True, upload_to='programe_de_studii/fise_disciplina/', verbose_name='Fisa disciplinei')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursuri', to='about.profesor')),
                ('specializare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursuri', to='programe_de_studii.specializare')),
            ],
            options={
                'verbose_name': 'Curs',
                'verbose_name_plural': 'Cursuri',
            },
        ),
    ]
