# Generated by Django 5.0.2 on 2024-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodCor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denumire", models.CharField(max_length=50)),
                ("cod", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Coduri COR",
                "verbose_name_plural": "Coduri COR",
            },
        ),
        migrations.AddField(
            model_name="specializare",
            name="detalii",
            field=models.TextField(blank=True, null=True, verbose_name="Detalii"),
        ),
        migrations.AddField(
            model_name="specializare",
            name="imagine",
            field=models.ImageField(
                blank=True, null=True, upload_to="programe_de_studii/images/"
            ),
        ),
    ]
