# Generated by Django 5.0.2 on 2024-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0003_specializare_coduri_cor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializare",
            name="coduri_cor",
            field=models.ManyToManyField(
                blank=True, null=True, to="programe_de_studii.codcor"
            ),
        ),
    ]
