# Generated by Django 5.0.2 on 2024-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0005_specializare_numar_locuri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializare",
            name="numar_locuri",
            field=models.IntegerField(default=0, verbose_name="Numar de locuri"),
        ),
    ]
