# Generated by Django 5.0.2 on 2024-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0006_alter_specializare_numar_locuri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializare",
            name="nume",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
