# Generated by Django 5.0.2 on 2024-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0007_alter_specializare_nume"),
    ]

    operations = [
        migrations.AddField(
            model_name="specializare",
            name="acronim",
            field=models.CharField(default="", max_length=20),
        ),
    ]
