# Generated by Django 5.0.2 on 2024-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0008_specializare_acronim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specializare",
            name="coduri_cor",
            field=models.ManyToManyField(blank=True, to="programe_de_studii.codcor"),
        ),
    ]
