# Generated by Django 5.0.2 on 2024-02-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_profesor_poza"),
        ("programe_de_studii", "0009_alter_specializare_coduri_cor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curs",
            name="profesor",
        ),
        migrations.AddField(
            model_name="curs",
            name="profesori",
            field=models.ManyToManyField(to="about.profesor"),
        ),
    ]
