# Generated by Django 5.0.2 on 2024-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0010_remove_curs_profesor_curs_profesori"),
    ]

    operations = [
        migrations.AddField(
            model_name="curs",
            name="obligatoriu",
            field=models.BooleanField(
                choices=[(True, "Obligatoriu"), (False, "Optional")], default=True
            ),
        ),
    ]
