# Generated by Django 5.0.2 on 2024-02-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0013_remove_specializare_plan_de_invatamant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plandeinvatamant",
            name="fisier",
            field=models.FileField(
                null=True, upload_to="programe_de_studii/planuri_de_invatamant/"
            ),
        ),
    ]
