# Generated by Django 5.0.2 on 2024-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0014_alter_plandeinvatamant_fisier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plandeinvatamant",
            name="an",
            field=models.IntegerField(
                choices=[(1, "Anul 1"), (2, "Anul 2"), (3, "Anul 3"), (4, "Anul 4")],
                default=1,
                unique=True,
            ),
        ),
    ]
