# Generated by Django 5.0.2 on 2024-02-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programe_de_studii", "0015_alter_plandeinvatamant_an"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orar",
            name="orar",
            field=models.FileField(
                null=True, upload_to="programe_de_studii/orare/", verbose_name="Orar"
            ),
        ),
    ]
