# Generated by Django 4.1.4 on 2023-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('prenume', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('grad', models.CharField(max_length=30)),
                ('birou', models.CharField(max_length=10)),
                ('cv', models.FileField(blank=True, null=True, upload_to='about/cvs/', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesori',
            },
        ),
    ]
