# Generated by Django 5.0.2 on 2024-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_profesor_poza"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="obligatoriu",
            field=models.BooleanField(
                choices=[(True, "Obligatoriu"), (False, "Optional")], default=True
            ),
        ),
    ]
