# Generated by Django 5.0.2 on 2024-02-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_profesor_obligatoriu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profesor",
            name="obligatoriu",
        ),
    ]
