# Generated by Django 4.1.4 on 2023-03-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Fisier')),
            ],
            options={
                'verbose_name': 'Fisier',
                'verbose_name_plural': 'Fisiere',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('files', models.ManyToManyField(blank=True, related_name='folders', to='files.file')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Foldere',
            },
        ),
    ]
