# Generated by Django 4.1.4 on 2023-03-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_remove_folder_files_remove_folder_parent_delete_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='/home/sorinandres/Desktop/upg_ime/files/FILE_STORAGE/<django.db.models.query_utils.DeferredAttribute object at 0x7f7ce76464a0>', editable=False, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Root',
                'verbose_name_plural': 'Roots',
            },
        ),
    ]
