# Generated by Django 4.1.4 on 2023-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Root',
        ),
    ]
