# Generated by Django 5.0.2 on 2024-02-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_files_delete_root"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="files",
            options={"verbose_name": "Acceseaza", "verbose_name_plural": "Acceseaza"},
        ),
    ]
