# Generated by Django 5.0.2 on 2024-02-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("about", "0005_profesor_organigrama"),
        ("programe_de_studii", "0017_alter_specializare_detalii"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denumire", models.CharField(max_length=300)),
                ("student", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=10)),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profesor",
                        to="about.profesor",
                    ),
                ),
                (
                    "specializare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profesor",
                        to="programe_de_studii.specializare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Examene",
            },
        ),
    ]
