# Generated by Django 5.0.2 on 2024-02-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examene", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examene",
            name="anul",
            field=models.IntegerField(
                choices=[
                    (0, "2020 - 2021"),
                    (1, "2021 - 2022"),
                    (2, "2022 - 2023"),
                    (3, "2023 - 2024"),
                    (4, "2024 - 2025"),
                    (5, "2025 - 2026"),
                    (6, "2026 - 2027"),
                    (7, "2027 - 2028"),
                ],
                default=0,
            ),
        ),
    ]
